### ISSUE TITLE
Type issues when customizing button styles in confirm dialog

### ISSUE THREAD

**Issue by Joebayld** [ThomasLeconte/vuetify3-dialog#11]
I'm trying to customize the button color of a confirm dialog, and it throws errors in typescript even though it's working. See screenshots.

<img width="393" alt="Screenshot 2024-01-21 at 7 06 58 PM" src="https://github.com/ThomasLeconte/vuetify3-dialog/assets/9399317/0a0da9e8-66bd-4af0-8f67-3ac42ccdca2f">
<img width="666" alt="Screenshot 2024-01-21 at 7 07 06 PM" src="https://github.com/ThomasLeconte/vuetify3-dialog/assets/9399317/262b5480-0ec2-4308-a46a-3208802ad039">

**Comment by Joebayld** [comment]
Also - it would be a breaking change but what if we made all the arguments a single interface? That way if you want to modify one thing you don't need to pass a bunch of empty arguments.

**Comment by ThomasLeconte** [comment]
Hi @Joebayld, thanks for issue reporting. 
`confirmDialog` allow you to customize your cancel or confirm button, but you must provide at least `title` and `key` properties to avoid library issues. After provided it, you will be able to customize color like you tried !
Here is type defined for button customization, it's a custom extension of Vuetify default button props :

```ts
export type DialogButton = Omit<Omit<VBtn['$props'], 'text'>, 'key'> & { title: string; key: string | boolean };
```

<br><br>

> Also - it would be a breaking change but what if we made all the arguments a single interface? That way if you want to modify one thing you don't need to pass a bunch of empty arguments.

Good suggeston! I will work on it soon !

**Comment by ThomasLeconte** [comment]
Hi again, last version (1.4.4) let you use one interface like you suggested!
