### ISSUE TITLE
confirm dialog not vertically centered

### ISSUE THREAD

**Issue by Joebayld** [ThomasLeconte/vuetify3-dialog#12]
I've noticed that the dialogs are not centered vertically. I would think it should do that by default. Any ideas?

<img width="1205" alt="Screenshot 2024-01-21 at 7 08 51 PM" src="https://github.com/ThomasLeconte/vuetify3-dialog/assets/9399317/fe99f982-ff98-4624-9afb-6d5347304392">

**Comment by ThomasLeconte** [comment]
Hi!
I've fixed issue in last version of lib : v1.4.4

=> Solution : https://github.com/vuetifyjs/vuetify/issues/15843
