### ISSUE TITLE
Vuetify 3.5.17 breaks Snackbar/notify

### ISSUE THREAD

**Issue by Shaxine** [ThomasLeconte/vuetify3-dialog#16]
It seems that Vuetify 3.5.17 added **(VSnackbar): position based on app layout**: https://github.com/vuetifyjs/vuetify/commit/cbb945d68086044f04cb13ef245dc4b4cb73392 which breaks the mount of the snakbar component.

```
[Vue warn]: injection "Symbol(vuetify:layout)" not found. 
  at <VSnackbar class="vuetify3-dialog-snackbar" timeout=3000 location="top right"  ... > 
  at <Snackbar text="Hello world!" level=undefined location="top right"  ... > [runtime-core.esm-bundler.js:47:12](http://localhost:3000/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js)

[Vue warn]: Unhandled error during execution of setup function 
  at <VSnackbar class="vuetify3-dialog-snackbar" timeout=3000 location="top right"  ... > 
  at <Snackbar text="Hello world!" level=undefined location="top right"  ... > [runtime-core.esm-bundler.js:47:12](http://localhost:3000/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js)

Uncaught (in promise) Error: [Vuetify] Could not find injected layout
    useLayout layout.ts:92
    setup VSnackbar.tsx:99
    setup defineComponent.tsx:121
...
```

I could reproduce the error after upgrading vuetify version of the test setup to 3.5.17.

**Comment by ThomasLeconte** [comment]
Hi 👋 Thanks for report. I think it should works but, because of app layout dependency, it will not work on my lib actually. In fact, everytime you show a new snackbar, a new Vue App is created. I can't make single app instance with all my custom components inside it.

By the way, I saw this alternative, I will test it soon : https://stackoverflow.com/a/75750575

**Comment by ThomasLeconte** [comment]
Hi 👋 Thanks for report!
I fixed it (https://github.com/ThomasLeconte/vuetify3-dialog/commit/2a5246048ae66114d39cdfbd79efe19c1658a00b) in new version `1.4.7` 😉

**Comment by Shaxine** [comment]
Thank you for the quick fix! I can confirm that it's working!
