### ISSUE TITLE
plugin uses a different vue app

### ISSUE THREAD

**Issue by georgios-v** [ThomasLeconte/vuetify3-dialog#20]
The different Notifiers are calling `createApp` and end up placing themselves in a new Vue app than the one actually running.  For example [here](https://github.com/ThomasLeconte/vuetify3-dialog/blob/a411028eed2920efd7f1f7dace92825dc0c1d440/src/Snackbar.ts#L49). Instead it should use the already available `this._app`.

There are various issues created by this which are ignored in trivial test apps but are highly prevalent in a production ready app. First and foremost a dialog cannot create a new notification using `this.$notify` because the plugin itself has not been installed in the new Vue app instance. Similarly, all other plugins are missing like Pinia, so stores cannot be accessed via `this.$storeName`. Finally, the notifications are never placed in the right location.

A solution to all of the above and more problems is to use `this._app` where `createApp` is called. As a side benefit, then vuetify is also present and doesn't need to be passed into the plugin during initialization.

**Comment by ThomasLeconte** [comment]
Hello ! You literally blown my mind, thanks a lot it was obvious but i didn't saw it sooner. I will fix this within next few days !

**Comment by ThomasLeconte** [comment]
Hi! Plugin now use project app instance, you should access to `this.$storeName` or whatever you want now ! I will fix snackbars positions later, priority was for first issue you mentionned.
I've just published the fix, you can upgrade package to v`1.5.0`.
