### ISSUE TITLE
Syntax check error when use the plugin

### ISSUE THREAD

**Issue by ramseyfeng** [ThomasLeconte/vuetify3-dialog#22]
IntelliJ throws an error like the screenshot below, according to the type definition, it seems vuetify should be passed in the options?

<img width="673" alt="image" src="https://github.com/ThomasLeconte/vuetify3-dialog/assets/2835062/20d4b90a-8aa7-42be-b185-2a4f954dcca5">

```
export type PluginOptions = {
  vuetify: Plugin;
  defaults?: {
    dialog?: {
      component?: VDialog['$props'];
      card?: VCard['$props'];
    };
    notify?: VSnackbar['$props'];
    bottomSheet?: VBottomSheet['$props'];
  };
};
```

**File: cypress/test-server/src/plugins/index.ts**

I tried it with `app.use(Vuetify3Dialog, {vuetify, defaults: {}}).mount('#app');` in my app, it works without any error hint. But when I do the same thing in the test-server, it is still not working...

**Comment by ThomasLeconte** [comment]
Hi! It has been fixed in last version `1.5.1` !
