### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "htmlContent". Expected String, got Boolean with value false.

### ISSUE THREAD

**Issue by renyancheng** [ThomasLeconte/vuetify3-dialog#28]
![image](https://github.com/user-attachments/assets/9a81fc97-cab5-4766-8f07-79cdaccffd60)
This warning occurs when I call notifyError. How do I clear this warning?
![image](https://github.com/user-attachments/assets/884190b9-c168-47e3-9dd1-8cb00b7e7440)

**Comment by ThomasLeconte** [comment]
Hi, thanks for issue ! It has been fixed in [last commit](https://github.com/ThomasLeconte/vuetify3-dialog/commit/4cdcfe2f453be0f245829d72856067a90fef0c30), I will wait for critical issue to publish this fix at same time !

**Comment by ThomasLeconte** [comment]
Hi! Last version `1.5.4` includes fix for this issue 😉
