### ISSUE TITLE
Error in README documentation : notify.warning => notify.warn

### ISSUE THREAD

**Issue by sbernard31** [ThomasLeconte/vuetify3-dialog#30]
The readme says: 

> There is 4 levels of severity : info, success, warning and error.

But it should be : 

> There is 4 levels of severity : info, success, **warn**~ing~ and error.

**Comment by ThomasLeconte** [comment]
Hello,
Thanks for issue report. Unfortunaly, i can't find "warn" in my codebase, have you file where it's used ?
- In[src/index.d.ts](https://github.com/ThomasLeconte/vuetify3-dialog/blob/master/src/index.d.ts), it's declared as `warning` (line 21)
- In [src/type.ts](https://github.com/ThomasLeconte/vuetify3-dialog/blob/master/src/types.ts) too
- In [src/components/Snackbar.vue](https://github.com/ThomasLeconte/vuetify3-dialog/blob/master/src/components/Snackbar.vue) too

**Comment by sbernard31** [comment]
I think the related code is here : https://github.com/ThomasLeconte/vuetify3-dialog/blob/master/src/Snackbar.ts#L11

**Comment by ThomasLeconte** [comment]
Effectively, there was some `warn` instead of `warning` in codebase 😅 [It has been fixed](https://github.com/ThomasLeconte/vuetify3-dialog/commit/199976edecaa2736ba1efad5da59d55ea9af62d2) and will be deployed when a next critical issue will be detected! Thanks 😉

**Comment by sbernard31** [comment]
Thx for fixing this quickly :pray: .
I was thinking that you will fix the doc not the code.
Note that this choice will lead to API break and so doesn't really follow semantic versioning. 

I will need to remember that when I will upgrade, I need to change my code from **warn** => **warning**

**Comment by sbernard31** [comment]
maybe a better solution would be to keep both (**warn** and **warning**) and deprecate **warn** and only remove **warn** when you upgrade to v2.0

(I don't know really if deprecated is possible in javascript)
