### ISSUE TITLE
export `confirmDialog` in js but `confirm` in d.ts

### ISSUE THREAD

**Issue by bhuh12** [ThomasLeconte/vuetify3-dialog#4]
version: **1.3.0**

![image](https://github.com/ThomasLeconte/vuetify3-dialog/assets/9862292/de601a79-e14b-4e2c-8694-e1e1a45d95ea)

![image](https://github.com/ThomasLeconte/vuetify3-dialog/assets/9862292/bd7af367-fc10-474e-bfae-1fbc36acdb8b)

![image](https://github.com/ThomasLeconte/vuetify3-dialog/assets/9862292/1e0f118f-1b49-4d3d-a5e1-ef5322bcfa77)

**Comment by ThomasLeconte** [comment]
Fixed in [this commit](https://github.com/ThomasLeconte/vuetify3-dialog/commit/fe28dd79b531ed9119df5f977ee568d19a1977df), thanks !
