### ISSUE TITLE
export pluginOptions type

### ISSUE THREAD

**Issue by GaborTorma** [ThomasLeconte/vuetify3-dialog#5]
Please `export type pluginOptions`.
I would like to create a nuxt module for your project, but I need the plugin options for typesafe configuring the module.

**Comment by GaborTorma** [comment]
Maybe exporting type CreateDialogOptions, CreateNotifyOptions and CreateBottomSheetOptions also would helpful for later use.

**Comment by ThomasLeconte** [comment]
Done in [1.3.2](https://github.com/ThomasLeconte/vuetify3-dialog/commit/2171e6782e40d37e8e8cba8c927a05ab2eea0a62), upgrade your package.json to include this new version 😉

**Comment by GaborTorma** [comment]
Thanx, nuxt module is ready: [@gabortorma/nuxt-vuetify3-dialog](https://github.com/GaborTorma/nuxt-vuetify3-dialog)

**Comment by ThomasLeconte** [comment]
Nice, I will add it on the README.md soon 😉
