### ISSUE TITLE
Closing custom dialog has no animation

### ISSUE THREAD

**Issue by Joebayld** [ThomasLeconte/vuetify3-dialog#7]
I made a dialog with a custom component, but when I call `$emit("closeDialog")` it closes the dialog immediately and doesn't do the fade animation. I think the issue is happening here: 

```javascript
resolve(value);
_app.unmount();
document.body.removeChild(div);
```

Perhaps it needs some sort of delay before removing from the document dom?

**Comment by ThomasLeconte** [comment]
Hey ! Thanks for report, it has been fixed in my last version `1.4.2` 😉
More details in [this commit](https://github.com/ThomasLeconte/vuetify3-dialog/commit/e6b0471077d10ed00160dcd4e40c099f23b47173)
