### ISSUE TITLE
Stack multiple notifications

### ISSUE THREAD

**Issue by Joebayld** [ThomasLeconte/vuetify3-dialog#9]
It would be nice to support a stack of notifications when multiple are presented at once. Currently when you receive multiple notifications they fall on top of each other, but having a vertical stack would be nice so you can see more than one. 

I'll try and work on this - but for now just starting a ticket.

**Comment by ThomasLeconte** [comment]
Nice Idea ! But actually, everytime a notification is created, a new Vue context is loaded too. Working with only one new context dedicated to the Plugin could be useful for your Idea !

**Comment by Joebayld** [comment]
Check this out. they do it already but for vue 2. 

https://github.com/yariksav/vuetify-dialog

**Comment by ThomasLeconte** [comment]
> Check this out. they do it already but for vue 2.
> 
> https://github.com/yariksav/vuetify-dialog

Hi, I don't know if you worked on it, but I started something, it works, I will release it soon after some tests !
https://github.com/ThomasLeconte/vuetify3-dialog/commit/a857e5e2821a86c6c20bd87f06c0171549d97c3a

**Comment by ThomasLeconte** [comment]
Hi, `1.4.3` version is now available and solve your problem.

**Comment by Joebayld** [comment]
Was thinking we should re-open this based on the new feature Vuetify 3 added. https://github.com/vuetifyjs/vuetify/issues/2384

I haven't dug into it but looks like they're going to do the work for stacking notifications natively!
